# Generated by Django 2.2.2 on 2020-10-15 00:03

from django.db import migrations, models
import rm_mask.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rm_mask.models.destination)),
            ],
        ),
    ]
